### ISSUE TITLE
No static method AFKeystoreWrapper()Lcom/appsflyer/internal/a; in class Lcom/appsflyer/internal/a; or its super classes (declaration of 'com.appsflyer.internal.a' appears in base.apk!classes2.dex)

### ISSUE THREAD

**Issue by linversion** [AppsFlyerSDK/appsflyer-android-app#16]
got this error
No static method AFKeystoreWrapper()Lcom/appsflyer/internal/a; in class Lcom/appsflyer/internal/a; or its super classes (declaration of 'com.appsflyer.internal.a' appears in base.apk!classes2.dex)

device: android samsung s20
appsflyer version: 6.4.3
com.android.installreferrer:installreferrer:1.1

proguard: 
-keep class com.appsflyer.** { *; }
-keep public class com.android.installreferrer.** { *; }

**Comment by ge-af** [comment]
Hi @linversion 

Please see this same [issue](https://github.com/AppsFlyerSDK/appsflyer-android-sdk/issues/38).
You can follow it if needed.
