### ISSUE TITLE
NullPointerException

### ISSUE THREAD

**Issue by AlexeyGodyaev** [AppsFlyerSDK/appsflyer-android-app#17]
java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String java.lang.String.replaceAll(java.lang.String, java.lang.String)' on a null object reference
	at com.appsflyer.internal.AFd1uSDK.values(AFd1uSDK.java:4121)
	at com.appsflyer.internal.AFc1hSDK.AFInAppEventType(AFc1hSDK.java:94)
	at com.appsflyer.internal.AFc1lSDK$4.run(AFc1lSDK.java:109)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:764)

**Comment by AlexeyGodyaev** [comment]
implementation 'com.appsflyer:af-android-sdk:6.8.0'

**Comment by pazlavi** [comment]
👋 Hi @AlexeyGodyaev and Thank you for reaching out to us.
In order for us to provide optimal support, please submit a ticket to our support team at support@appsflyer.com.
When submitting the ticket, please specify:
- ✅ your AppsFlyer sign-up (account) email
- ✅ app ID
- ✅ production steps
- ✅ logs
- ✅ code snippets
- ✅ and any additional relevant information.

**Comment by AlexeyGodyaev** [comment]
While I'm waiting for an employee to contact you, could you tell me if it's possible to send your own events without parameters. Example:

fun sendEvent(context: Context, nameEvent: String, valueParams: Map<String, Any>?) {
        AppsFlyerLib.getInstance().logEvent(context, nameEvent, valueParams ?: mapOf())
    }

**Comment by AlexeyGodyaev** [comment]
sdk update procedure
... -> 6.5.2 -> 6.6.1 -> 6.7.0 -> 6.8.0

**Comment by pazlavi** [comment]
@AlexeyGodyaev 
It is possible to send an empty map and also `null`. 
Does this crash happen on specific devices or Android versions? 
Are you able to reproduce this crash?  If so, please provide steps to reproduce, code snippets, and debug logs.

**Comment by pazlavi** [comment]
@AlexeyGodyaev 
Please try v6.8.1.

**Comment by jarredt** [comment]
@AlexeyGodyaev wondering if updating fixed for you?

**Comment by jarredt** [comment]
@pazlavi do you know if this issue is fixed in 6.8.2? The Android SDK [release notes](https://support.appsflyer.com/hc/en-us/articles/115001256006) don't refer to a bugfix for this. We experienced this issue when using 6.8.0 via the React Native SDK, so I'm trying to figure out if it's safe for me to try the latest version of the React Native SDK, which uses Android 6.8.2.

**Comment by pazlavi** [comment]
@jarredt, it was fixed in 6.8.1
