### ISSUE TITLE
EXC_BAD_ACCESS at __swizzled_continueUserActivity

### ISSUE THREAD

**Issue by keitanxkeitan** [AppsFlyerSDK/appsflyer-android-app#21]
Hello. I'm developing a game with Unity and trying to support OneLink for iOS.

When clicking a OneLink, my app gets frozen. This happens only when the app is in background. Therefore, this doesn't happen when the app is killed. iOS version is 15.4.1.

Do you think you can help me?

Sorry but I couldn't get stack trace. So I pasted screenshots.

EXC_BAD_ACCESS happens at [UnityAppController application:continueUserActivity:restorationHandler]. And the method is called from __swizzled_continueUserActivity.

**UnityAppController.m**
<img width="1216" alt="Screen Shot 2023-02-08 at 20 59 44" src="https://user-images.githubusercontent.com/851007/217524010-2af160db-0786-45ec-b647-6e56aaab9ada.png">

**AppsFlyer+AppController.m**
<img width="1216" alt="Screen Shot 2023-02-08 at 21 00 02" src="https://user-images.githubusercontent.com/851007/217524030-cbbed5df-d53f-42d0-83f4-1e728852b0c4.png">

**Comment by pazlavi** [comment]
@keitanxkeitan This is the wrong repo. Please contact our Support team.
