### ISSUE TITLE
SingleInstallBroadcastReceiver security warning in AndroidManifest.xml

### ISSUE THREAD

**Issue by mtsahakis** [AppsFlyerSDK/appsflyer-android-app#9]
When I use

```
<receiver
            android:name="com.appsflyer.SingleInstallBroadcastReceiver"
            android:exported="true">
            <intent-filter>
                <action android:name="com.android.vending.INSTALL_REFERRER" />
            </intent-filter>
</receiver>
```

I receive a warning in Android Studio "Exported receiver does not require permission"

If we add 

`android:permission="android.permission.INSTALL_PACKAGES"`

The notification goes away. Can you verify if the SDK will then work as expected?

**Comment by afdima** [comment]
Switch to google play referrer library instead of broadcast receiver https://support.appsflyer.com/hc/en-us/articles/207032126-Android-SDK-integration-for-developers#integration-22-adding-android-install-referrer-to-your-app
